.TH bcftools 1 "14 October 2013" "bcftools-0.0.1" "Bioinformatics tools"
.SH NAME
.PP
bcftools - Utilities for the Binary Call Format (BCF) and VCF
.SH SYNOPSIS
.PP
bcftools index in.bcf
.PP
bcftools view in.bcf chr2:100-200 > out.vcf
.PP
bcftools view -Nvm0.99 in.bcf > out.vcf 2> out.afs

.SH DESCRIPTION
.PP
Samtools is a set of utilities that manipulate alignments in the BAM
format. It imports from and exports to the SAM (Sequence Alignment/Map)
format, does sorting, merging and indexing, and allows to retrieve reads
in any regions swiftly.

Samtools is designed to work on a stream. It regards an input file `-'
as the standard input (stdin) and an output file `-' as the standard
output (stdout). Several commands can thus be combined with Unix
pipes. Samtools always output warning and error messages to the standard
error output (stderr).

.SH COMMANDS AND OPTIONS

.TP 10
.B view
.B bcftools view
.RB [ \-AbFGNQSucgv ]
.RB [ \-D
.IR seqDict ]
.RB [ \-l
.IR listLoci ]
.RB [ \-s
.IR listSample ]
.RB [ \-i
.IR gapSNPratio ]
.RB [ \-t
.IR mutRate ]
.RB [ \-p
.IR varThres ]
.RB [ \-m
.IR varThres ]
.RB [ \-P
.IR prior ]
.RB [ \-1
.IR nGroup1 ]
.RB [ \-d
.IR minFrac ]
.RB [ \-U
.IR nPerm ]
.RB [ \-X
.IR permThres ]
.RB [ \-T
.IR trioType ]
.I in.bcf
.RI [ region ]

Convert between BCF and VCF, call variant candidates and estimate allele
frequencies.

.RS
.TP
.B Input/Output Options:
.TP 10
.B -A
Retain all possible alternate alleles at variant sites. By default, the view
command discards unlikely alleles.
.TP 10
.B -b
Output in the BCF format. The default is VCF.
.TP
.BI -D \ FILE
Sequence dictionary (list of chromosome names) for VCF->BCF conversion [null]
.TP
.B -F
Indicate PL is generated by r921 or before (ordering is different).
.TP
.B -G
Suppress all individual genotype information.
.TP
.BI -l \ FILE
List of sites at which information are outputted [all sites]
.TP
.B -N
Skip sites where the REF field is not A/C/G/T
.TP
.B -Q
Output the QCALL likelihood format
.TP
.BI -s \ FILE
List of samples to use. The first column in the input gives the sample names
and the second gives the ploidy, which can only be 1 or 2. When the 2nd column
is absent, the sample ploidy is assumed to be 2. In the output, the ordering of
samples will be identical to the one in
.IR FILE .
[null]
.TP
.B -S
The input is VCF instead of BCF.
.TP
.B -u
Uncompressed BCF output (force -b).
.TP
.B Consensus/Variant Calling Options:
.TP 10
.B -c
Call variants using Bayesian inference. This option automatically invokes option
.BR -e .
.TP
.BI -d \ FLOAT
When
.B -v
is in use, skip loci where the fraction of samples covered by reads is below FLOAT. [0]
.TP
.B -e
Perform max-likelihood inference only, including estimating the site allele frequency,
testing Hardy-Weinberg equlibrium and testing associations with LRT.
.TP
.B -g
Call per-sample genotypes at variant sites (force -c)
.TP
.BI -i \ FLOAT
Ratio of INDEL-to-SNP mutation rate [0.15]
.TP
.BI -m \ FLOAT
New model for improved multiallelic and rare-variant calling. Another
ALT allele is accepted if P(chi^2) of LRT exceeds the FLOAT threshold. The 
parameter seems robust and the actual value usually does not affect the results
much; a good value to use is 0.99. This is the recommended calling method. [0]
.TP
.BI -p \ FLOAT
A site is considered to be a variant if P(ref|D)<FLOAT [0.5]
.TP
.BI -P \ STR
Prior or initial allele frequency spectrum. If STR can be
.IR full ,
.IR cond2 ,
.I flat
or the file consisting of error output from a previous variant calling
run.
.TP
.BI -t \ FLOAT
Scaled muttion rate for variant calling [0.001]
.TP
.BI -T \ STR
Enable pair/trio calling. For trio calling, option
.B -s
is usually needed to be applied to configure the trio members and their ordering.
In the file supplied to the option
.BR -s ,
the first sample must be the child, the second the father and the third the mother.
The valid values of
.I STR
are `pair', `trioauto', `trioxd' and `trioxs', where `pair' calls differences between two input samples, and `trioxd' (`trioxs') specifies that the input
is from the X chromosome non-PAR regions and the child is a female (male). [null]
.TP
.B -v
Output variant sites only (force -c)
.TP
.B Contrast Calling and Association Test Options:
.TP
.BI -1 \ INT
Number of group-1 samples. This option is used for dividing the samples into
two groups for contrast SNP calling or association test.
When this option is in use, the following VCF INFO will be outputted:
PC2, PCHI2 and QCHI2. [0]
.TP
.BI -U \ INT
Number of permutations for association test (effective only with
.BR -1 )
[0]
.TP
.BI -X \ FLOAT
Only perform permutations for P(chi^2)<FLOAT (effective only with
.BR -U )
[0.01]
.RE

.TP
.B index
.B bcftools index
.I in.bcf

Index sorted BCF for random access.
.RE

.TP
.B cat
.B bcftools cat
.I in1.bcf
.RI [ "in2.bcf " [ ... "]]]"

Concatenate BCF files. The input files are required to be sorted and
have identical samples appearing in the same order.
.RE

.SH EXAMPLES
.IP o 2
Call SNPs and short INDELs for one diploid individual:

  samtools mpileup -ugf ref.fa aln.bam | bcftools view -bvcg - > var.raw.bcf
  bcftools view var.raw.bcf | vcfutils.pl varFilter -D 100 > var.flt.vcf

The
.B -D
option of varFilter controls the maximum read depth, which should be
adjusted to about twice the average read depth.  One may consider to add
.B -C50
to
.B mpileup
if mapping quality is overestimated for reads containing excessive
mismatches. Applying this option usually helps
.B BWA-short
but may not other mappers.

.IP o 2
Generate the consensus sequence for one diploid individual:

  samtools mpileup -uf ref.fa aln.bam | bcftools view -cg - | vcfutils.pl vcf2fq > cns.fq

.IP o 2
Call somatic mutations from a pair of samples:

  samtools mpileup -DSuf ref.fa aln.bam | bcftools view -bvcgT pair - > var.bcf

In the output INFO field,
.I CLR
gives the Phred-log ratio between the likelihood by treating the
two samples independently, and the likelihood by requiring the genotype to be identical.
This
.I CLR
is effectively a score measuring the confidence of somatic calls. The higher the better.

.IP o 2
Call de novo and somatic mutations from a family trio:

  samtools mpileup -DSuf ref.fa aln.bam | bcftools view -bvcgT pair -s samples.txt - > var.bcf

File
.I samples.txt
should consist of three lines specifying the member and order of samples (in the order of child-father-mother).
Similarly,
.I CLR
gives the Phred-log likelihood ratio with and without the trio constraint.
.I UGT
shows the most likely genotype configuration without the trio constraint, and
.I CGT
gives the most likely genotype configuration satisfying the trio constraint.

.IP o 2
Call SNPs and short indels for multiple diploid individuals:

  samtools mpileup -P ILLUMINA -ugf ref.fa *.bam | bcftools view -bcvg - > var.raw.bcf
  bcftools view var.raw.bcf | vcfutils.pl varFilter -D 2000 > var.flt.vcf

Individuals are identified from the
.B SM
tags in the
.B @RG
header lines. Individuals can be pooled in one alignment file; one
individual can also be separated into multiple files. The
.B -P
option specifies that indel candidates should be collected only from
read groups with the
.B @RG-PL
tag set to
.IR ILLUMINA .
Collecting indel candidates from reads sequenced by an indel-prone
technology may affect the performance of indel calling.

Note that there is a new calling model which can be invoked by

    bcftools view -m0.99  ...

which fixes some severe limitations of the default method.

For filtering, best results seem to be achieved by first applying the
.IR SnpGap
filter and then applying some machine learning approach

    vcf-annotate -f SnpGap=n
    vcf filter ...

Both can be found in the 
.B vcftools
and
.B htslib
package (links below).

.IP o 2
Derive the allele frequency spectrum (AFS) on a list of sites from multiple individuals:

  samtools mpileup -Igf ref.fa *.bam > all.bcf
  bcftools view -bl sites.list all.bcf > sites.bcf
  bcftools view -cGP cond2 sites.bcf > /dev/null 2> sites.1.afs
  bcftools view -cGP sites.1.afs sites.bcf > /dev/null 2> sites.2.afs
  bcftools view -cGP sites.2.afs sites.bcf > /dev/null 2> sites.3.afs
  ......

where
.I sites.list
contains the list of sites with each line consisting of the reference
sequence name and position. The following
.B bcftools
commands estimate AFS by EM.

.SH AUTHOR
.PP
Heng Li from the Sanger Institute wrote the C version of samtools. Bob
Handsaker from the Broad Institute implemented the BGZF library and Jue
Ruan from Beijing Genomics Institute wrote the RAZF library. John
Marshall and Petr Danecek contribute to the source code and various
people from the 1000 Genomes Project have contributed to the SAM format
specification.

.SH SEE ALSO
.IR samtools (1),
.IR sam (5),
.IR vcf (5)
.PP
Samtools website: <http://samtools.sourceforge.net>
.br
Bcftools latest source: <https://github.com/samtools/bcftools>
.br
VCFtools website with stable link to VCF specification: <http://vcftools.sourceforge.net>
.br
HTSlib website: <https://github.com/samtools/htslib>
