.TH bcftools 1 "22 October 2013" "bcftools-0.2.0" "Bioinformatics tools"
.SH NAME
.PP
bcftools - Utilities for calling variants and manipulating VCFs and BCFs
.SH SYNOPSIS
.PP
.B bcftools
[\fICOMMAND\fR] [\fIOPTIONS\fR]
.br
.B bcftools
.br
.B bcftools
[\fICOMMAND\fR]

.SH DESCRIPTION
.PP
Bcftools is a set of utilities that manipulate variant calls in the Variant
Call Format (VCF) and its binary counterpart BCF. All commands work
transparently with both VCFs and BCFs, both uncompressed and BGZF-compressed.

Bcftools is designed to work on a stream. It regards an input file "-"
as the standard input (stdin) and an output file "-" as the standard
output (stdout). Several commands can thus be combined with Unix
pipes.

.SH COMMANDS
For a full list of available commands, run 
.B bcftools 
without arguments:
.TP 10
.B tabix
    tabix for BGZF'd BED, GFF, SAM, VCF and more
.TP 10
.B index 
    index BCF
.TP 10
.B call
    SNP/indel calling, this is the former \fBview\fR command
.TP 10          
.B filter 
    filter VCF/BCF files using fixed thresholds
.TP 10          
.B gtcheck
    tool for detecting swaps and contaminations
.TP 10          
.B isec
    intersections of VCF/BCF files
.TP 10          
.B merge
    merge VCF/BCF files
.TP 10          
.B norm
    normalize indels to common representation
.TP 10          
.B query
    transform VCF/BCF into user-defined formats
.TP 10          
.B stats
    produce VCF/BCF stats (former vcfcheck)
.TP 10          
.B subset
    subset and filter VCF/BCF
.TP 10          
.B view
    VCF<->BCF conversion

.SH OPTIONS

For a list of options, run 
.B bcftools 
[\fICOMMAND\fR]
without arguments.

.SH EXAMPLES
todo

.SH AUTHORS
.PP
Heng Li from the Sanger Institute wrote the original C version of htslib,
samtools and bcftools. Bob Handsaker from the Broad Institute implemented the
BGZF library. John Marshall and Petr Danecek are maintaining and further
developing the package. 
Many other people contributed to the file format specifications and to the
program, both directly and indirectly by providing patches, testing and reporting
bugs. 

.SH BUG REPORTS 
.PP
Please report any bugs you encounter on the github website: <http://github.com/samtools/bcftools>

.SH SEE ALSO
.PP
Bcftools documentation: <http://vcftools.sourceforge.net/htslib.html>
.br
Bcftools website: <http://github.com/samtools/bcftools>
.br
Samtools website: <http://github.com/samtools/samtools>
.br
HTSlib website: <http://github.com/samtools/htslib>
.br
VCFtools website with stable link to VCF specification: <http://vcftools.sourceforge.net>

