
[role='navig']
****

.General
* link:index.html[Main page]
* link:../bcftools.html[Manual page]
* link:install.html[Installation]
* link:publications.html[Publications]

.Calling
* link:cnv-calling.html[CNV calling]
* link:csq-calling.html[Consequence calling]
* link:consensus-sequence.html[Consensus calling]
* link:roh-calling.html[ROH calling]
* link:variant-calling.html[Variant calling and filtering]

.Tips and Tricks
* link:convert.html[Converting formats]
* link:annotate.html[Adding annotation]
* link:query.html[Extracting information]
* link:filtering.html[Filtering expressions]
* link:scaling.html[Performance and Scaling]
* link:plugins.html[Plugins]
* link:FAQ.html[FAQ]

****

// Disable last updated text.
:last-update-label!:


++++
<div id="main">
++++

